---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
  - name: pcf-pipelines
  - name: opsman-metadata
  - name: terraform-state

outputs:
  - name: terraform-state-output

run:
  path: pcf-pipelines/install-pcf/azure/tasks/iaas/deploy-iaas.sh

params:
  azure_pcf_terraform_template:
  azure_subscription_id:
  azure_tenant_id:
  azure_service_principal_id:
  azure_service_principal_password:
  azure_region:
  azure_terraform_prefix:
  azure_vm_admin:
  azure_vm_password:
  pcf_ert_domain:
  pcf_opsman_admin:
  pcf_opsman_admin_passwd:
  pcf_ssh_key_pub:
  azure_multi_resgroup_network:
  azure_multi_resgroup_pcf:
  azure_multi_resgroup_infra_subnet_name:
  azure_multi_resgroup_infra_vnet_name:
  azure_terraform_vnet_cidr:
  azure_terraform_subnet_infra_cidr:
  azure_terraform_subnet_ert_cidr:
  azure_terraform_subnet_services1_cidr:
  azure_terraform_subnet_dynamic_services_cidr:
